---
services:
  db:
    image: redis:6
    container_name: redis
    ports: 
      - "6379:6379"
  
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/python-flask
